// <auto-generated />
using GraphQLDemo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraphQLDemo.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20260712054207_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("GraphQLDemo.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Frank Herbert",
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 2,
                            Author = "William Gibson",
                            Title = "Neuromancer"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Isaac Asimov",
                            Title = "Foundation"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Neal Stephenson",
                            Title = "Snow Crash"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Dan Simmons",
                            Title = "Hyperion"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
