// <auto-generated />
using GraphQLDemo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraphQLDemo.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20260726052546_AddUser")]
    partial class AddUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("GraphQLDemo.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Frank Herbert",
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 2,
                            Author = "William Gibson",
                            Title = "Neuromancer"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Isaac Asimov",
                            Title = "Foundation"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Neal Stephenson",
                            Title = "Snow Crash"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Dan Simmons",
                            Title = "Hyperion"
                        });
                });

            modelBuilder.Entity("GraphQLDemo.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            Content = "A sprawling, essential classic.",
                            Rating = 5
                        },
                        new
                        {
                            Id = 2,
                            BookId = 1,
                            Content = "Dense but rewarding.",
                            Rating = 4
                        },
                        new
                        {
                            Id = 3,
                            BookId = 2,
                            Content = "Defined a genre.",
                            Rating = 5
                        });
                });

            modelBuilder.Entity("GraphQLDemo.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GraphQLDemo.Review", b =>
                {
                    b.HasOne("GraphQLDemo.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("GraphQLDemo.Book", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
